// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinClient uIFileDProgrammsetcConClient = this.UIFileDProgrammsetcConWindow.UIFileDProgrammsetcConClient;
            #endregion

            // Type 'a{Enter}' in 'file:///D:/Programms&etc/ConsoleApplication6/Conso...' client
            Keyboard.SendKeys(uIFileDProgrammsetcConClient, this.RecordedMethod1Params.UIFileDProgrammsetcConClientSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UICWindowssystem32cmdeWindow UICWindowssystem32cmdeWindow
        {
            get
            {
                if ((this.mUICWindowssystem32cmdeWindow == null))
                {
                    this.mUICWindowssystem32cmdeWindow = new UICWindowssystem32cmdeWindow();
                }
                return this.mUICWindowssystem32cmdeWindow;
            }
        }
        
        public UIFileDProgrammsetcConWindow UIFileDProgrammsetcConWindow
        {
            get
            {
                if ((this.mUIFileDProgrammsetcConWindow == null))
                {
                    this.mUIFileDProgrammsetcConWindow = new UIFileDProgrammsetcConWindow();
                }
                return this.mUIFileDProgrammsetcConWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UICWindowssystem32cmdeWindow mUICWindowssystem32cmdeWindow;
        
        private UIFileDProgrammsetcConWindow mUIFileDProgrammsetcConWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'a{Enter}' in 'file:///D:/Programms&etc/ConsoleApplication6/Conso...' client
        /// </summary>
        public string UIFileDProgrammsetcConClientSendKeys = "a{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UICWindowssystem32cmdeWindow : WinWindow
    {
        
        public UICWindowssystem32cmdeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "C:\\Windows\\system32\\cmd.exe";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ConsoleWindowClass";
            this.WindowTitles.Add("C:\\Windows\\system32\\cmd.exe");
            #endregion
        }
        
        #region Properties
        public WinClient UICWindowssystem32cmdeClient
        {
            get
            {
                if ((this.mUICWindowssystem32cmdeClient == null))
                {
                    this.mUICWindowssystem32cmdeClient = new WinClient(this);
                    #region Search Criteria
                    this.mUICWindowssystem32cmdeClient.SearchProperties[WinControl.PropertyNames.Name] = "C:\\Windows\\system32\\cmd.exe";
                    this.mUICWindowssystem32cmdeClient.WindowTitles.Add("C:\\Windows\\system32\\cmd.exe");
                    #endregion
                }
                return this.mUICWindowssystem32cmdeClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUICWindowssystem32cmdeClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFileDProgrammsetcConWindow : WinWindow
    {
        
        public UIFileDProgrammsetcConWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "file:///D:/Programms&etc/ConsoleApplication6/ConsoleApplication6/bin/Debug/Consol" +
                "eApplication6.EXE";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ConsoleWindowClass";
            this.WindowTitles.Add("file:///D:/Programms&etc/ConsoleApplication6/ConsoleApplication6/bin/Debug/Consol" +
                    "eApplication6.EXE");
            #endregion
        }
        
        #region Properties
        public WinClient UIFileDProgrammsetcConClient
        {
            get
            {
                if ((this.mUIFileDProgrammsetcConClient == null))
                {
                    this.mUIFileDProgrammsetcConClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIFileDProgrammsetcConClient.SearchProperties[WinControl.PropertyNames.Name] = "file:///D:/Programmsetc/ConsoleApplication6/ConsoleApplication6/bin/Debug/Console" +
                        "Application6.EXE";
                    this.mUIFileDProgrammsetcConClient.WindowTitles.Add("file:///D:/Programms&etc/ConsoleApplication6/ConsoleApplication6/bin/Debug/Consol" +
                            "eApplication6.EXE");
                    #endregion
                }
                return this.mUIFileDProgrammsetcConClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIFileDProgrammsetcConClient;
        #endregion
    }
}
